apiLink: 'https://api.github.com/repos/TreeboMC/TreeboTweaks/releases/latest'
releasePage: 'https://github.com/TreeboMC/TreeboTweaks/releases/latest'
checkUpdates: 'true'

bstatsIntegration: true


general:
  messages:
    badge: '&3[Treebo Tweaks]&r'
    error: '&4ERROR:&r'